#!/usr/bin/with-contenv bash

USERNAME=${USERNAME:-"eyhn"}

if [ ! -d /run/sshd ]; then
  mkdir /run/sshd
  chmod 0755 /run/sshd
fi

exec 2>&1 \
        s6-setuidgid ${USERNAME} /usr/sbin/sshd -D -e -p 2222