#!/usr/bin/with-contenv bash

set -e

USERNAME=${USERNAME:-"eyhn"}
USER_UID=${USER_UID:-"automatic"}
USER_GID=${USER_GID:-"automatic"}

# Create or update a non-root user to match UID/GID.
if [ "${USERNAME}" != "root" ]; then
    if id -u ${USERNAME} > /dev/null 2>&1; then
        # User exists, update if needed
        if [ "${USER_GID}" != "automatic" ] && [ "$USER_GID" != "$(id -G $USERNAME)" ]; then 
            groupmod --gid $USER_GID $USERNAME 
            usermod --gid $USER_GID $USERNAME
        fi
        if [ "${USER_UID}" != "automatic" ] && [ "$USER_UID" != "$(id -u $USERNAME)" ]; then 
            usermod --uid $USER_UID $USERNAME
        fi
    else
        # Create user
        if [ "${USER_GID}" = "automatic" ]; then
            groupadd $USERNAME
        else
            groupadd --gid $USER_GID $USERNAME
        fi
        if [ "${USER_UID}" = "automatic" ]; then 
            useradd -s /bin/bash --gid $USERNAME -m $USERNAME
        else
            useradd -s /bin/bash --uid $USER_UID --gid $USERNAME -m $USERNAME
        fi
    fi
fi

# Add add sudo support for non-root user
if [ "${USERNAME}" != "root" ]; then
    echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME
    chmod 0440 /etc/sudoers.d/$USERNAME
fi

if [ "${USERNAME}" != "root" ]; then
    chown ${USERNAME}:${USERNAME} "/home/${USERNAME}"
fi