name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and push images
        run: |
          chmod +x ./ci.sh
          ./ci.sh ${{ secrets.CR_PAT }}